- sh_script/conf/pyproject.toml
- sh_script/pytest.ini
- sh_script/test_vtpm.py
- sh_script/vtpmtool.py
Add test cases：
nvread & nvwrite & nvextend
unseal
loadexternal
pcrread (replay pcr0 with event log)
pcrextend
quote
Fix #13
> CI: Add test cases for TPM command

- Cargo.lock
- deps/rust-tpm-20-ref/smallc/include/time.h
- deps/rust-tpm-20-ref/smallc/src/time.c
- src/tpm/Cargo.toml
- src/tpm/src/lib.rs
- src/tpm/src/rtc.rs
> Implement time

- sh_script/pytest.ini
- sh_script/test_vtpm.py
- sh_script/vtpmtool.py
1. Optimization(merge event_log, acpi, rtmr to 1 test case), refactor the waiting logic, Fix #26  
2. Update test case: reset user td
> CI integration test case update

- src/protocol/src/report_status/command.rs
- src/protocol/src/report_status/response.rs
- src/protocol/src/service/command.rs
- src/protocol/src/service/response.rs
- src/protocol/src/wait_for_request/command.rs
- src/protocol/src/wait_for_request/response.rs
> Determine whether the buffer length is valid in src/protocol

- sh_script/pytest.ini
- sh_script/test_vtpm.py
1. Add test case 'Simple attestation with tpm2-tools', Fix #41 
2. Fix random fail issue
3. Disable warning in pytest
> Update integration test in CI

- .cargo/config.toml
> Remove the alias for xbuild in cargo/config.toml

- .github/workflows/unittest.yml
- src/protocol/src/service/command.rs
> Fix the error in unittest

- src/crypto/src/ek_cert.rs
- src/crypto/src/resolve.rs
- src/crypto/src/x509.rs
- src/tpm/src/lib.rs
- src/tpm/src/tpm2_provision.rs
> Update ca-cert and ek-cert based on vtpm/ek-credential spec

- src/global/src/lib.rs
- src/global/src/tpm.rs
- src/spdm/src/vtpm_io_transport.rs
- src/tpm/src/lib.rs
- src/tpm/src/std_lib.rs
- src/tpm/src/tpm2_ca_cert.rs
- src/tpm/src/tpm2_cmd_rsp/getcaps.rs
- src/tpm/src/tpm2_provision.rs
- src/vtpmtd/src/vtpm/spdm_cbs.rs
- src/vtpmtd/src/vtpm/spdm_connection.rs
- src/vtpmtd/src/vtpm/spdm_server.rs
> Provision ek.v4

- src/crypto/src/ek_cert.rs
- src/crypto/src/resolve.rs
> src/crypto: update ca cert with VTPMTD_CA_EXTENDED_KEY_USAGE

- sh_script/conf/pyproject.toml
- sh_script/test_vtpm.py
- sh_script/vtpmtool.py
Test destroy instance
Test reset user td
> CI: Add more test cases

- Cargo.lock
- config/metadata.json
- config/shim_layout.json
- sh_script/build.sh
- src/vtpmtd/Cargo.toml
- src/vtpmtd/src/main.rs
- src/vtpmtd/src/vtpm/spdm_server.rs
> Metadata.v2

- src/attestation/src/root_ca.rs
- src/crypto/src/ek_cert.rs
- src/tpm/src/tpm2_cmd_rsp/getcaps.rs
> Fix warnings reports by MIRAI

- .github/dependabot.yml
Use dependabot to make automatic dependency updates.
> github: enable dependabot

- src/crypto/src/ek_cert.rs
- src/crypto/src/resolve.rs
> Fix the wrong signature algorithm when generation x509 cert

- src/spdm/src/crypto_callback.rs
- src/tpm/src/tpm2_ca_cert.rs
- src/tpm/src/tpm2_provision.rs
> clear the sensitive key data after using

- src/protocol/src/report_status/command.rs
- src/protocol/src/report_status/response.rs
- src/protocol/src/wait_for_request/command.rs
- src/protocol/src/wait_for_request/response.rs
- src/tdtunnel/src/td_tunnel.rs
> rename TDVM_ID to TPM_ID

- sh_script/conf/pyproject.toml
- sh_script/launch_vtpm_td.sh
- sh_script/test_vtpm.py
1. Add test case kill vTPM TD during running
2. Add test case to verify CA
3. Update memory to 32M of launch_vtpm_td.sh
> Add more test case in CI

- sh_script/test_vtpm.py
- sh_script/vtpmtool.py
> add test case to cover more tpm commands 

- src/crypto/src/ek_cert.rs
- src/global/src/tpm.rs
- src/tpm/src/tpm2_provision.rs
> Ek subject alt name

- src/tpm/src/tpm2_provision.rs
Fix #124 
The x_size / y_size of ecp384 public key are not always 48. They shall be read from TPM2B_PUBLIC.
> Get the ecp384 public key from TPM2B_PUBLIC

- .github/workflows/integration.yml
- doc/integration-test.md
- sh_script/conf/pyproject.toml
- sh_script/integration_test.py
- sh_script/utils.py
> Cleanup integration test code and add readme

- sh_script/integration_test.py
> Fix test case verify_CA_and_EK_certificate

- README.md
- sh_script/launch_user_td.sh
- sh_script/launch_vtpm_td.sh
> Turn of debug in launching script

- .github/workflows/main.yml
- deps/rust-tpm-20-ref/sh_script/build.sh
- deps/rust-tpm-20-ref/sh_script/rename_smallc_symbols
- sh_script/build.sh
- sh_script/launch_vtpm_td.sh
- src/global/src/lib.rs
- src/vtpmtd/Cargo.toml
> Fix the failure of getting td_quote

- src/tdtunnel/src/interrupt.rs
> src/tdtunnel: use tdvmcall_sti_halt instead of tdvmcall_halt

- README.md
- doc/verify-vtpm-features.md
> Add doc to introduce quote verification test

- sh_script/conf/pyproject.toml
- sh_script/integration_test.py
- sh_script/utils.py
> Enable quote verification test in CI integration test

- .github/workflows/main.yml
- Cargo.lock
- src/attestation/src/ghci.rs
- src/crypto/Cargo.toml
- src/eventlog/Cargo.toml
- src/eventlog/src/eventlog.rs
- src/tdtunnel/src/td_tunnel.rs
- src/vtpmtd/Cargo.toml
- src/vtpmtd/src/main.rs
Fix: security issue zerocopy upgrade to the latest version 0.7.31
> Upgrade Zerocop to 0.7.31 and deps/td-shim

- .gitmodules
- Cargo.lock
- Cargo.toml
- README.md
- sh_script/build.sh
- sh_script/pre-build.sh
- src/crypto/Cargo.toml
- src/crypto/fuzz/Cargo.toml
- src/spdm/Cargo.toml
- src/spdm/src/crypto_callback.rs
- src/spdm/src/vtpm_io_transport.rs
- src/spdm/src/vtpm_transport_encap.rs
- src/tpm/Cargo.toml
- src/tpm/src/tpm2_ca_cert.rs
- src/tpm/src/tpm2_provision.rs
- src/vtpmtd/Cargo.toml
- src/vtpmtd/src/vtpm/spdm_cbs.rs
- src/vtpmtd/src/vtpm/spdm_connection.rs
Fix: #149 
I built the vtpmtd locally successfully and got all unit tests pass.
> Replace submodule Rust-SPDM with SPDM-rs

- sh_script/integration_test.py
> Fix quote_verification test case copy ca_cert fail randomly

- .github/workflows/format.yml
- .github/workflows/integration.yml
- .github/workflows/main.yml
- .github/workflows/unittest.yml
- Dockerfile
- README.md
> Update yml files toolchain from nightly-2023-08-28 to nightly-2023-12-31
